//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapClusterRoleBinding) DeepCopyInto(out *LdapClusterRoleBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapClusterRoleBinding.
func (in *LdapClusterRoleBinding) DeepCopy() *LdapClusterRoleBinding {
	if in == nil {
		return nil
	}
	out := new(LdapClusterRoleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LdapClusterRoleBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapClusterRoleBindingList) DeepCopyInto(out *LdapClusterRoleBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LdapClusterRoleBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapClusterRoleBindingList.
func (in *LdapClusterRoleBindingList) DeepCopy() *LdapClusterRoleBindingList {
	if in == nil {
		return nil
	}
	out := new(LdapClusterRoleBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LdapClusterRoleBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapClusterRoleBindingSpec) DeepCopyInto(out *LdapClusterRoleBindingSpec) {
	*out = *in
	out.ClusterRoleRef = in.ClusterRoleRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapClusterRoleBindingSpec.
func (in *LdapClusterRoleBindingSpec) DeepCopy() *LdapClusterRoleBindingSpec {
	if in == nil {
		return nil
	}
	out := new(LdapClusterRoleBindingSpec)
	in.DeepCopyInto(out)
	return out
}
