apiVersion: v2
name: kerbernetes
description: Kerbernetes is a Kubernetes authentication service integrating Kerberos and LDAP.
type: application
version: "1.0.8"
appVersion: "v1.0.0"
icon: https://raw.githubusercontent.com/froz42/kerbernetes/refs/heads/main/assets/kerbernetes_tiny.png
keywords:
  - kubernetes
  - kerberos
  - ldap
home: https://github.com/froz42/kerbernetes
sources:
  - https://github.com/froz42/kerbernetes
maintainers:
  - name: Froz
    email: froz@42paris.fr
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/category: security
