apiVersion: v1
kind: Service
metadata:
  name: {{ include "kerbernetes-api.fullname" . }}
  labels:
    {{ include "kerbernetes-api.appLabel" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.httpPort }}
      protocol: TCP
      name: http
  selector:
    {{ include "kerbernetes-api.appLabel" . }}
